Syntax 7

SectionUseCase."HiFi" {
	Comment "Default"
	Define.SpeakerDevice "0"
	Define.PlaybackChannels "4"
	Define.MicDevice "1"
	Define.JackDevice "2"
	Define.HeadsetDevice "3"
	File "/AppleT2/HiFi.conf"
}
