Syntax 6

SectionUseCase."HiFi" {
	Comment "Play HiFi quality Music"
	Define.SpeakerDevice "0"
	Define.PlaybackChannels "2"
	Define.SpeakerChannelMap "FL,FR"
	Define.MicDevice "1"
	Define.JackDevice "2"
	Define.HeadsetDevice "3"
	File "/AppleT2/HiFi.conf"
}
