SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speakers"

	Value {
		PlaybackPriority 50
		PlaybackPCM "hw:${CardId},${var:SpeakerDevice}"
		PlaybackChannels "${var:PlaybackChannels}"
		PlaybackChannelMap "${var:SpeakerChannelMap}"
		PlaybackName "Speakers"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	Value {
		PlaybackPriority 2000
		PlaybackPCM "hw:${CardId},${var:JackDevice}"
		PlaybackChannels "2"
		PlaybackName "Headphones"
		JackControl "Codec Output Jack"
		JackDev "Apple T2 Audio Codec Output"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	Value {
		TQ Voice
		CapturePriority 100
		CapturePCM "hw:${CardId},${var:MicDevice}"
		CaptureChannels "3"
		CaptureChannelMap "FL,FR,FC"
		CaptureName "Internal Mic"
	}
}

SectionDevice."Headset" {
	Comment "Headset Microphone"

	Value {
		CapturePriority 300
		CapturePCM "hw:${CardId},${var:HeadsetDevice}"
		CaptureChannels "1"
		CaptureName "Headset Mic"
		JackControl "Codec Output Jack"
		JackDev "Apple T2 Audio Codec Output"
	}
}
