SectionDevice."Speaker" {
	Comment "Speaker"

	EnableSequence [
		cset "name='Master Playback Switch' on"
		cset "name='Speaker Playback Switch' on"
	]

	DisableSequence [
		cset "name='Speaker Playback Switch' off"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels "${var:SpeakerChannels}"
		PlaybackChannelMap "${var:SpeakerChannelMap}"
		PlaybackName "Speakers"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	EnableSequence [
		cset "name='Master Playback Switch' on"
		cset "name='Headphone Playback Switch' on"
	]

	DisableSequence [
		cset "name='Headphone Playback Switch' off"
	]

	Value {
		PlaybackPriority 300
		PlaybackPCM "hw:${CardId},2"
		PlaybackChannels "2"
		PlaybackName "Headphones"
		JackControl "Codec Output Jack"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},1"
		CaptureChannels "3"
		CaptureChannelMap "FL,FR,FC"
		CaptureName "Internal Mic"
	}
}

SectionDevice."Headset" {
	Comment "Headset Microphone"

	Value {
		CapturePriority 300
		CapturePCM "hw:${CardId},3"
		CaptureChannels "1"
		CaptureName "Headset Mic"
		JackControl "Codec Output Jack"
	}
}
