SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Internal Speakers"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},${var:SpeakerDevice}"
		PlaybackChannels "${var:PlaybackChannels}"
		PlaybackName "Speakers"
	}

	If.ch2 {
		Condition {
			Type String
			String1 "${var:PlaybackChannels}"
			String2 "2"
		}
		True.Value {
			PlaybackChannelPos0 "FL"
			PlaybackChannelPos1 "FR"
		}
	}

	If.ch4 {
		Condition {
			Type String
			String1 "${var:PlaybackChannels}"
			String2 "4"
		}
		True.Value {
			PlaybackChannelPos0 "FL"
			PlaybackChannelPos1 "FR"
			PlaybackChannelPos2 "RL"
			PlaybackChannelPos3 "RR"
		}
	}

	If.ch6 {
		Condition {
			Type String
			String1 "${var:PlaybackChannels}"
			String2 "6"
		}
		True.Value {
			PlaybackChannelPos0 "FL"
			PlaybackChannelPos1 "FR"
			PlaybackChannelPos2 "FC"
			PlaybackChannelPos3 "LFE"
			PlaybackChannelPos4 "RL"
			PlaybackChannelPos5 "RR"
		}
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	Value {
		PlaybackPriority 500
		PlaybackPCM "hw:${CardId},${var:JackDevice}"
		PlaybackChannels "2"
		PlaybackName "Headphones"
		JackControl "Codec Output Jack"
		JackDev "Apple T2 Audio Codec Output"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},${var:MicDevice}"
		CaptureName "Internal Mic"
		CaptureChannels 3
		CaptureChannelPos0 "AUX0"
		CaptureChannelPos1 "AUX1"
		CaptureChannelPos2 "AUX2"
	}
}

SectionDevice."Headset" {
	Comment "Headset Microphone"

	Value {
		CapturePriority 400
		CapturePCM "hw:${CardId},${var:HeadsetDevice}"
		CaptureChannels "1"
		CaptureName "Headset Mic"
		JackControl "Codec Output Jack"
		JackDev "Apple T2 Audio Codec Output"
	}
}
